- examples/genkit/retrievers-with-fga/README.md
- examples/genkit/retrievers-with-fga/scripts/fga-init.ts
- examples/langchain/retrievers-with-fga/README.md
- examples/langchain/retrievers-with-fga/scripts/fga-init.ts
- examples/llamaindex/retrievers-with-fga/README.md
- examples/llamaindex/retrievers-with-fga/scripts/fga-init.ts
- examples/openai-fga/README.md
- examples/openai-fga/scripts/fga-init.ts
- examples/openai-fga/src/fga-retriever.ts
- packages/ai-genkit/src/retrievers/fga-retriever.ts
- packages/ai-langchain/src/retrievers/fga-retriever.ts
- packages/ai-llamaindex/src/retrievers/fga-retriever.ts
When you create a new store in FGA, there is a modal that shows environment values to configure and so on. Here API_URL is shown instead of API_HOST and hence this change will make it less confusing to developers
> use apiUrl instead of apiHost to align with FGA docs

- demos/vercel-ai/lib/auth0-ai.ts
- packages/ai-vercel/README.md
- packages/ai-vercel/src/FederatedConnections/FederatedConnectionAuthorizer.ts
- packages/ai/src/authorizers/fedconn-authorizer.ts
This pull request includes several changes to the `auth0` integration and the `FederatedConnectionAuthorizer` classes to improve functionality and error handling. The most important changes include renaming a method, modifying token validation, and handling optional token responses.
* [`demos/vercel-ai/lib/auth0-ai.ts`](diffhunk://#diff-2e7e5a7b4ebf321c1df40b2d152370ccf27b48863cafbc1a02a094f8adf104f9L8-R13): Renamed `getRefreshToken` method to `refreshToken` and adjusted the connection string format.
* [`packages/ai-vercel/README.md`](diffhunk://#diff-6c7b20f5b315d5227899a28d3b17d1fd20266b33e2bb028eb4be0708458a79aeL42-R42): Updated the method name from `getRefreshToken` to `refreshToken` in the documentation.
* [`packages/ai-vercel/src/FederatedConnections/FederatedConnectionAuthorizer.ts` …
> fix fed connection demo

- packages/ai-vercel/src/FederatedConnections/FederatedConnectionAuthorizer.ts
- packages/ai-vercel/src/FederatedConnections/FederatedConnectionError.ts
- packages/ai-vercel/src/FederatedConnections/getFederatedConnectionAccessToken.ts
- packages/ai-vercel/tsconfig.json
- packages/ai/package.json
- packages/ai/src/TokenResponse.ts
- packages/ai/src/authorizers/federated-connections/asyncLocalStorage.ts
- packages/ai/src/authorizers/federated-connections/index.ts
- packages/ai/src/index.ts
- packages/ai/tsup.config.ts
This pull request includes several changes to the `ai-vercel` and `ai` packages, primarily focusing on refactoring imports, updating TypeScript configurations, and adding new type definitions. The most important changes are summarized below:
* [`packages/ai-vercel/src/FederatedConnections/FederatedConnectionAuthorizer.ts`](diffhunk://#diff-169a9509c62b0bd0cca1cc8da22f9348a4a2a876fc2b341b381a1deb658e6c04L2-R11): Updated imports to use `@auth0/ai` and `@auth0/ai/FederatedConnections` instead of `auth0/dist/cjs/auth/tokenExchange` and `@auth0/ai`.
* [`packages/ai-vercel/src/FederatedConnections/FederatedConnectionError.ts`](diffhunk://#diff-2cb917cab113fea89ae4ebbe38b3f5a9cbdec08e4cb8ad79cde98eb8d094e15fL1-L6): Changed import to directly import `asyncLocalStorage` from …
> refactor federated connection into namespace

- packages/ai-vercel/package.json
- packages/ai-vercel/src/CIBA/CIBAuthorizationError.ts
- packages/ai-vercel/test/CIBAAuthorizer.test.ts
- packages/ai/src/authorizers/ciba/index.ts
This pull request includes several significant changes to the `ai-vercel` package, focusing on updating dependencies, improving error handling, and adding comprehensive tests for the `CIBAAuthorizer` class. Below are the most important changes:
* Updated the `test` script in `package.json` to use `vitest` instead of a placeholder. (`packages/ai-vercel/package.json`, [packages/ai-vercel/package.jsonL17-R17](diffhunk://#diff-58aa606e03887c81c436e799d7cb8d4a0c422a590d7222c9905188dde4cd5afcL17-R17))
* Changed the import path for `asyncLocalStorage` in `CIBAuthorizationError.ts` to use the `CIBA` module instead of `FederatedConnections`. (`packages/ai-vercel/src/CIBA/CIBAuthorizationError.ts`, [packages/ai-vercel/src/CIBA/CIBAuthorizationError.tsL1-R1](diffhunk://#diff-76459a82cd60a65faef838748 …
> chore: add tests for CIBA in ai-vercel

- packages/ai-vercel/src/FederatedConnections/getFederatedConnectionAccessToken.ts
- packages/ai/src/authorizers/ciba/index.ts
- packages/ai/src/authorizers/federated-connections/asyncLocalStorage.ts
- packages/ai/src/authorizers/federated-connections/index.ts
- packages/ai/test/federated-connection-base.test.ts
This pull request includes several changes to the federated connections authorization process, focusing on simplifying the access token handling and improving the test coverage. The most important changes include replacing the `getAccessToken` method with the `accessToken` property, updating the `FederatedConnectionAuthorizerBase` class to use the new property, and adding comprehensive tests for the authorization process.
* [`packages/ai-vercel/src/FederatedConnections/getFederatedConnectionAccessToken.ts`](diffhunk://#diff-9ba234cadbc52942b8488636caf5ab40e505f907932b0ffdbd80de1978a9e26cL10-R10): Replaced the `getAccessToken` method with the `accessToken` property.
* [`packages/ai/src/authorizers/federated-connections/asyncLocalStorage.ts`](diffhunk://#diff-62f12e044ac6e60758f0c39f4b809e9d …
> refactor federated connections and add tests

- packages/ai-vercel/src/FederatedConnections/FederatedConnectionAuthorizer.ts
- packages/ai-vercel/test/FerderatedConnectionAuthorizer.test.ts
- packages/ai/src/authorizers/ciba/index.ts
- packages/ai/src/authorizers/federated-connections/index.ts
- packages/ai/src/errors.ts
- packages/ai/test/ciba-authorizer-base.test.ts
- packages/ai/test/federated-connection-base.test.ts
This pull request includes significant changes to the Federated Connection and CIBA authorizers in the `ai-vercel` package, focusing on error handling and test improvements. The most important changes are the introduction of a new `AuthorizationRequired` error, updates to error handling in the Federated Connection authorizer, and the removal of unnecessary code in the CIBA authorizer.
Error Handling Enhancements:
* updated the error handling method to throw a `FederatedConnectionError` when authorization is required. [[1]](diffhunk://#diff-169a9509c62b0bd0cca1cc8da22f9348a4a2a876fc2b341b381a1deb658e6c04L4-R4) [[2]](diffhunk://#diff-169a9509c62b0bd0cca1cc8da22f9348a4a2a876fc2b341b381a1deb658e6c04L14-L26)
* [`packages/ai/src/authorizers/federated-connections/index.ts`](diffhunk://#diff-06f1c …
> chore: refactor federated connections

- demos/vercel-ai-agent/.env.example
- demos/vercel-ai-agent/src/queue/index.ts
This pull request includes the addition of a new example environment configuration file for the Vercel AI Agent demo. The file provides placeholders for necessary environment variables and instructions for obtaining the required API keys and configuration values.
Environment configuration:
* [`demos/vercel-ai-agent/.env.example`](diffhunk://#diff-59cebb98f6577e80e498d7f097fc12def99385b346b04d3144fb93191bac9b6aR1-R18): Added example environment configuration file with placeholders for OpenAI API Key, Auth0 configuration, Redis configuration, and Maildev configuration.
> chore: add .env.example to vercel-ai-agent demo

- packages/ai-vercel/README.md
- packages/ai-vercel/src/Auth0AI.ts
- packages/ai-vercel/src/FGA/FGAAuthorizer.ts
- packages/ai-vercel/src/FGA/index.ts
- packages/ai-vercel/src/FGA_AI.ts
- packages/ai-vercel/src/index.ts
- packages/ai/package.json
- packages/ai/src/authorizers/ciba/index.ts
- packages/ai/src/authorizers/federated-connections/index.ts
- packages/ai/src/authorizers/fga/index.ts
- packages/ai/src/parameters.ts
- packages/ai/test/fga-authorizer-base.test.ts
- packages/ai/tsup.config.ts
This pull request introduces several significant changes to the `ai-vercel` package, focusing on adding Fine-Grained Authorization (FGA) support and refactoring existing authorizers. The most important changes include adding a new FGA authorizer, updating the `Auth0AI` class to use a more generic parameter type, and refactoring the existing CIBA and Federated Connection authorizers to use a new parameter resolution utility.
* [`packages/ai-vercel/src/FGA/FGAAuthorizer.ts`](diffhunk://#diff-5efa2d654056ea2400cdf06315825a07398a2e6ac7dceeeb8ef7305aff6f7a11R1-R34): Introduced the `FGAAuthorizer` class, which implements FGA authorization control for AI tools.
* [`packages/ai-vercel/src/FGA_AI.ts`](diffhunk://#diff-0624e89037a24d1a91918660e0a99cc5c59142a5b3b9ef0a417aa0b640650953R1-R52): Added …
> feat: add FGAAuthorizerBase in @auth0/ai and FGAAuthorizer for @auth0/ai-vercel

- demos/vercel-ai-agent/src/tools/buySock.ts
- packages/ai-vercel/README.md
- packages/ai-vercel/src/CIBA/index.ts
- packages/ai-vercel/src/index.ts
This pull request introduces several changes related to the integration of Client Initiated Backchannel Authentication (CIBA) in the `ai-vercel` package and its usage in the `vercel-ai-agent` demo. The main updates include importing and using the `getCIBACredentials` function, updating the `buyStock` tool, and enhancing documentation with examples of using CIBA.
* [`demos/vercel-ai-agent/src/tools/buySock.ts`](diffhunk://#diff-d961e96c50d00b93aa9adb919e04172fcfad84b92d7d823afdfdf3f009477792R3-R22): Imported the `getCIBACredentials` function and added its usage to log the access token obtained with CIBA during the execution of the `buyStock` tool. [[1]](diffhunk://#diff-d961e96c50d00b93aa9adb919e04172fcfad84b92d7d823afdfdf3f009477792R3-R22) …
> chore: improve ciba docs and sample

- packages/ai/src/authorizers/ciba-authorizer.ts
- packages/ai/src/authorizers/ciba/index.ts
This pull request includes changes to the `CIBAAuthorizer` and `CIBAAuthorizerBase` classes to improve type consistency and ensure correct data handling. The most important changes include updating the type of `requestExpiry` from `string` to `number` and modifying how `requestExpiry` is converted to a string.
Type and data handling improvements:
* [`packages/ai/src/authorizers/ciba-authorizer.ts`](diffhunk://#diff-251f2a3ff9bd69fa8f227004619422bbce40825076d5394df5424c24202c4958L15-R15): Changed the type of `requestExpiry` from `string` to `number` in the `CibaAuthorizerOptions` type and updated the `CIBAAuthorizer` class to convert `requestExpiry` to a string. [[1]](diffhunk://#diff-251f2a3ff9bd69fa8f227004619422bbce40825076d5394df5424c24202c4958L15-R15) …
> chore: change requestExpiry to number

- .github/workflows/ci.yaml
- demos/nextjs-ai/package.json
- package-lock.json
- package.json
- packages/ai-genkit/package.json
- packages/ai-genkit/test/index.test.ts
- packages/ai-langchain/eslint.config.mjs
- packages/ai-langchain/package.json
- packages/ai-langchain/src/ciba/ciba-graph/initialize-ciba.ts
- packages/ai-langchain/src/retrievers/fga-retriever.ts
- packages/ai-langchain/test/index.test.ts
- packages/ai-llamaindex/eslint.config.mjs
- packages/ai-llamaindex/package.json
- packages/ai-llamaindex/test/index.test.ts
- packages/ai-vercel/eslint.config.mjs
- packages/ai-vercel/package.json
- turbo.json
This pull request includes several changes to improve linting configurations, update dependencies, and clean up test files across multiple packages. The most important changes include adding linting steps to CI workflows, updating `package.json` scripts, and enhancing ESLint configurations.
* [`.github/workflows/ci.yaml`](diffhunk://#diff-944291df2c9c06359d37cc8833d182d705c9e8c3108e7cfe132d61a06e9133ddR35-R46): Added a linting step to the CI workflow to ensure code quality.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L7-R8): Added a `lint` script to run linting across the codebase.
* [`packages/ai-genkit/package.json`](diffhunk://#diff-c6a418b63601c8cd1ebb9280658c36c7afce12b9a7444a40705de54d18c1c983L15-R15): Updated the `lint` script …
> chore: add lint to CI

- .github/workflows/ci.yaml
- .husky/commit-msg
- .husky/install.mjs
- .husky/pre-commit
- commitlint.config.js
- package-lock.json
- package.json
This pull request includes an update to the CI workflow configuration in the `.github/workflows/ci.yaml` file to add a new step for validating commit messages. The most important change is the addition of a commit message validation step that runs only for pull requests.
CI workflow improvements:
* [`.github/workflows/ci.yaml`](diffhunk://#diff-944291df2c9c06359d37cc8833d182d705c9e8c3108e7cfe132d61a06e9133ddR35-R38): Added a step to validate commit messages using `commitlint` for pull requests. This ensures that all commit messages follow the project's conventions.
> chore: validate commit messages format to enable continuous release

- examples/async-user-confirmation/README.md
- examples/authorization-for-rag/README.md
- examples/calling-apis/README.md
This pull request includes updates to the documentation for various examples in the Auth0 AI SDK. The changes primarily involve adding diagrams and explanations to improve clarity and understanding.
Key updates to the documentation:
* [`examples/async-user-confirmation/README.md`](diffhunk://#diff-8254fc62a007a6a24ead6df7398765329238da392eafbe127123b122faf4eeebR15-R32): Added a high-level workflow diagram for Async User Confirmation.
* [`examples/authorization-for-rag/README.md`](diffhunk://#diff-26bc98b91d933bf6892d97da85c7fef009b818030b3e9a9d995e03c8c662e610L17-R20): Updated the existing diagram with a new image and added styling for better visual presentation.
* [`examples/calling-apis/README.md`](diffhunk://#diff-3e8ba4fae20cf9fd511889810d9d83e80a4391f3ca9f6c8a6b5a854b999f6376R1-R30): …
> chore(docs): add calling-apis examples folder and diagrams

- packages/ai/src/authorizers/federated-connections/index.ts
- packages/ai/test/federated-connection-base.test.ts
This pull request includes several updates to improve code formatting, add new dependencies, and enhance the functionality of the `FederatedConnectionAuthorizerBase` class. The most important changes include adding new dependencies to `package.json`, updating ESLint configurations, and improving the handling of access tokens in the `FederatedConnectionAuthorizerBase` class.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R14-R16): Added `eslint-config-prettier` and `prettier` to `devDependencies`.
* [`packages/ai/package.json`](diffhunk://#diff-3758ea4fd63e4789bf712baab7b4b0227fce843a17e2ed535091b9c3b83ff2dfL48-R50): Replaced `@eslint/js` with `@eslint/compat` and updated `eslint` to version 9.22.0.
* …
> chore: add accessToken to federated connection authorizer

- demos/nextjs-ai/components/chat.tsx
- demos/nextjs-ai/components/langgraph/chat.tsx
- demos/vercel-ai-agent/src/worker/handlers/conditional_trade.ts
- packages/ai-vercel/src/interrupts/errorSerializer.ts
- packages/ai-vercel/test/CIBAAuthorizer.test.ts
- packages/ai/src/authorizers/ciba/index.ts
- packages/ai/src/authorizers/fga/index.ts
- packages/ai/src/interrupts/Auth0Interrupt.ts
- packages/ai/src/interrupts/CIBAInterrupts.ts
- packages/ai/src/interrupts/FederatedConnectionInterrupt.ts
- packages/ai/src/interrupts/index.ts
- packages/ai/test/ciba-authorizer-base.test.ts
- packages/ai/test/fga-authorizer-base.test.ts
- packages/ai/test/interrupts.test.ts
This pull request includes several changes to the `Auth0Interrupt` class and its related interrupt classes, aiming to standardize the naming and handling of interrupts, as well as improving type safety and readability. The most important changes include modifying how interrupts are checked, renaming interrupt classes for consistency, and updating relevant imports and usage throughout the codebase.
Improvements to interrupt handling:
* [`packages/ai/src/interrupts/Auth0Interrupt.ts`](diffhunk://#diff-321bfe64e1e811f14b66e4a912fff5bedfe91a30247b1badd0944c1edf876fb6R1-L10): Introduced a type alias `Auth0InterruptData` for generalized interrupt types, standardized the `toJSON` method, and updated the `isInterrupt` method to assert the data part of the interrupt. …
> chore: refactor interrupts

- demos/vercel-ai-agent/package.json
- package-lock.json
- packages/ai-genkit/package.json
- packages/ai-langchain/package.json
- packages/ai-llamaindex/package.json
- packages/ai-vercel/package.json
This pull request involves the removal of the `z` package from various `package.json` files across multiple projects. The most important changes include the deletion of the `z` package from the dependencies in several files.
Package cleanup:
* [`demos/vercel-ai-agent/package.json`](diffhunk://#diff-962c68ed2310e64e35f08c59dfa5523724c8b6dcf657f14eafb89541be373d43L30): Removed the `z` package from dependencies.
* [`packages/ai-genkit/package.json`](diffhunk://#diff-c6a418b63601c8cd1ebb9280658c36c7afce12b9a7444a40705de54d18c1c983L36-R36): Removed the `z` package from dependencies.
* [`packages/ai-langchain/package.json`](diffhunk://#diff-2d0aede74b38e61ff841e237af368e676506ebaf46f123bbe7ed389a86df0bd6L36-R36): Removed the `z` package from dependencies.
* …
> chore(dep): remove z as dependency

- demos/nextjs-ai/package.json
- demos/vercel-ai-agent/package.json
- examples/async-user-confirmation/ai-sdk/package.json
- examples/async-user-confirmation/genkit/package.json
- examples/async-user-confirmation/langchain/package.json
- examples/async-user-confirmation/llamaindex/package.json
- examples/async-user-confirmation/sample-api/package.json
- examples/authorization-for-rag/genkit/package.json
- examples/authorization-for-rag/langchain/package.json
- examples/authorization-for-rag/langgraph-agentic/package.json
- examples/authorization-for-rag/langgraph-stategraph/package.json
- examples/authorization-for-rag/llamaindex/package.json
- examples/authorization-for-tools/ai-sdk/package.json
- examples/authorization-for-tools/genkit/package.json
- examples/authorization-for-tools/langchain/package.json
- examples/authorization-for-tools/llamaindex/package.json
- examples/calling-apis/langgraph/package.json
- package-lock.json
This pull request includes multiple changes to the `package.json` files across various demo and example projects. The main goal of these changes is to update the package names and ensure they are marked as private.
Changes to package names and privacy settings:
* [`demos/nextjs-ai/package.json`](diffhunk://#diff-b4894c0d871d44213386cc0cdcacc5a5b1efcc6738a3d63e5002ab48409076d3L2-R4): Updated package name to `@auth0/auth0-ai-js-demos-nextjs-ai` and added `private: true`.
* [`demos/vercel-ai-agent/package.json`](diffhunk://#diff-962c68ed2310e64e35f08c59dfa5523724c8b6dcf657f14eafb89541be373d43L2-R4): Updated package name to `@auth0/auth0-ai-js-demos-vercel-ai-agent` and added `private: true`.
Updates to async-user-confirmation examples:
* …
> chore(docs): update all exampels and demos pkg names and privacy

- examples/async-user-confirmation/llamaindex/package.json
- examples/authorization-for-rag/llamaindex/package.json
- examples/authorization-for-tools/llamaindex/package.json
- package-lock.json
- packages/ai-llamaindex/package.json
This pull request includes updates to the `llamaindex` dependency across multiple package files to ensure consistency and compatibility with the latest version.
Dependency updates:
* [`examples/async-user-confirmation/llamaindex/package.json`](diffhunk://#diff-05accadc4d4c0b2674b39d2342d4105bc457f9447b30a4cc3ca97f39af59beb8L18-R18): Updated `llamaindex` dependency from `^0.8.32` to `^0.9.0`.
* [`examples/authorization-for-rag/llamaindex/package.json`](diffhunk://#diff-6cb58049ea850cb1d7e62474016c2633a3860a2f825d48c91fdaedcdac471717L18-R18): Updated `llamaindex` dependency from `^0.8.32` to `^0.9.0`.
* [`examples/authorization-for-tools/llamaindex/package.json`](diffhunk://#diff-0cbbcd66f0a3008925336a3306d47150973f93a39d61ea9f3dfb17a8a6405350L18-R18): Updated `llamaindex` dependency from …
> chore(dep): bump llamaindex@0.9.0 on examples

- packages/ai-genkit/src/FGA/FGAAuthorizer.ts
- packages/ai-genkit/src/FGA_AI.ts
This pull request includes changes to the `FGAAuthorizer` and `FGA_AI` classes in the `ai-genkit` package to improve the handling and protection of tool functions with Fine Grained Authorization (FGA). The most important changes include modifying the `authorizer` method, updating type definitions, and adding detailed documentation comments.
Improvements to `FGAAuthorizer`:
* [`packages/ai-genkit/src/FGA/FGAAuthorizer.ts`](diffhunk://#diff-6919fa3301b57265b62f1a39d60d389b474b126c7b1f4c16bccda0b67c22b46fL25-R26): Modified the `authorizer` method to simplify the function signature and improve type safety by changing the generic parameters to a more flexible function type.
Updates to type definitions:
* [`packages/ai-genkit/src/FGA_AI.ts`](diffhunk://#diff-cbe71f3d03323933978fc762065cfb36ce971 …
> chore: fix generic types for genkit

- packages/ai-components/.releaserc.json
- packages/ai-genkit/.releaserc.json
- packages/ai-langchain/.releaserc.json
- packages/ai-llamaindex/.releaserc.json
- packages/ai-vercel/.releaserc.json
- packages/ai/.releaserc.json
- tools/semantic-release/.releaserc.json
This pull request includes changes to the release configuration files for multiple packages. The primary change is the addition of the `semantic-release-monorepo` extension to the `.releaserc.json` files of various packages.
Changes to release configuration:
* [`packages/ai-components/.releaserc.json`](diffhunk://#diff-397596fdb288d89c5288937b87cf0f650724fc7df2c0a81cfd9463b61f513350L2-R5): Added `semantic-release-monorepo` extension.
* [`packages/ai-genkit/.releaserc.json`](diffhunk://#diff-397596fdb288d89c5288937b87cf0f650724fc7df2c0a81cfd9463b61f513350L2-R5): Added `semantic-release-monorepo` extension.
* [`packages/ai-langchain/.releaserc.json`](diffhunk://#diff-397596fdb288d89c5288937b87cf0f650724fc7df2c0a81cfd9463b61f513350L2-R5): Added `semantic-release-monorepo` extension.
* …
> chore: fix semantic-release config

- packages/ai-components/package.json
- packages/ai-genkit/package.json
- packages/ai-langchain/package.json
- packages/ai-llamaindex/package.json
- packages/ai-vercel/package.json
- packages/ai/package.json
This pull request includes changes to multiple `package.json` files across various packages to add a `publishConfig` section. This change ensures that the packages are published with public access.
Changes to `package.json` files:
* [`packages/ai-components/package.json`](diffhunk://#diff-2f50ec3821f5cb76a6ae462829b37d48d92bea37bce79c2d36e7bd0bfcc93472R28-R30): Added `publishConfig` section to set access to public.
* [`packages/ai-genkit/package.json`](diffhunk://#diff-c6a418b63601c8cd1ebb9280658c36c7afce12b9a7444a40705de54d18c1c983R49-R51): Added `publishConfig` section to set access to public.
* [`packages/ai-langchain/package.json`](diffhunk://#diff-2d0aede74b38e61ff841e237af368e676506ebaf46f123bbe7ed389a86df0bd6R58-R60): Added `publishConfig` section to set access to public.
* …
> chore: fix publishConfig in package.json

- .github/workflows/release.yaml
This pull request includes a change to the GitHub Actions workflow configuration to improve the release process. The most important change is switching the trigger for the release workflow from a push event to a workflow run completion event.
Changes to GitHub Actions workflow configuration:
* [`.github/workflows/release.yaml`](diffhunk://#diff-e426ed45842837026e10e66af23d9c7077e89eacbe6958ce7cb991130ad05adaL4-R9): Changed the trigger for the release workflow from a push to the `main` branch to the completion of the Continuous Integration workflow on the `main` branch.
> chore: fix release workflow

- packages/ai-langchain/README.md
This pull request includes changes to the `packages/ai-langchain/README.md` file to improve the tool definition and usage pattern for the `buyTool` function. The most important changes include modifying the `buyTool` definition to use `useFGA` and adjusting the function's structure for better clarity and functionality.
Improvements to tool definition and usage pattern:
* [`packages/ai-langchain/README.md`](diffhunk://#diff-8fb1cf4cde044d4166b3bda4d69c651c166999d1c6eb19a8b25446dde5036628L99-R103): Modified the `buyTool` definition to use `useFGA` directly and restructured the function to improve clarity and functionality. [[1]](diffhunk://#diff-8fb1cf4cde044d4166b3bda4d69c651c166999d1c6eb19a8b25446dde5036628L99-R103) [[2]](diffhunk://#diff-8fb1cf4cde044d4166b3bda4d69c651c166999d1c6eb19a8b25 …
> fix: fga example in langchain docs

- package-lock.json
- package.json
- packages/ai-genkit/package.json
- packages/ai-langchain/package.json
- packages/ai-llamaindex/package.json
- packages/ai-vercel/package.json
- packages/ai/package.json
This pull request includes updates to several package dependencies across multiple files. The most important changes involve updating the versions of `vite` and `vitest` dependencies.
Dependency updates:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L34-R34): Updated `vite` dependency from version `^6.2.1` to `^6.2.3`.
* `packages/ai-genkit/package.json`, `packages/ai-langchain/package.json`, `packages/ai-llamaindex/package.json`, `packages/ai-vercel/package.json`, `packages/ai/package.json`: Updated `vitest` dependency from version `^3.0.8` to `^3.0.9`. [[1]](diffhunk://#diff-c6a418b63601c8cd1ebb9280658c36c7afce12b9a7444a40705de54d18c1c983L48-R48) [[2]](diffhunk://#diff-2d0aede74b38e61ff841e237af368e676506ebaf46f123bbe7ed389a86df0bd6L5 …
> chore(dep): update vite dependency

- demos/nextjs-ai/package.json
- examples/async-user-confirmation/langgraph/package.json
- examples/authorization-for-tools/langchain/package.json
- examples/calling-apis/langgraph/package.json
- package-lock.json
- packages/ai-langchain/package.json
- packages/ai/src/authorizers/ciba/CIBAAuthorizerBase.ts
- packages/ai/src/authorizers/ciba/CIBAAuthorizerParams.ts
This pull request updates the version of the `@langchain/langgraph-sdk` package across various files to ensure consistency and compatibility with the latest features and fixes.
Dependency updates:
* Updated `@langchain/langgraph-sdk` version to `^0.0.57` in `demos/nextjs-ai/package.json`
* Updated `@langchain/langgraph-sdk` version to `^0.0.57` in `examples/async-user-confirmation/langgraph/package.json`
* Updated `@langchain/langgraph-sdk` version to `^0.0.57` in `examples/authorization-for-tools/langchain/package.json`
* Updated `@langchain/langgraph-sdk` version to `^0.0.57` in `examples/calling-apis/langgraph/package.json`
* Updated `@langchain/langgraph-sdk` version to `^0.0.57` in `packages/ai-langchain/package.json`
> chore(deps): fix package-lock.json bumping @langchain/langgraph-sdk@0.0.57

- packages/ai/src/interrupts/Auth0Interrupt.ts
This prevents errors when calling `FederatedConnectionInterrupt.isInterrupt(toolInterrupt)` such as when calling the weather tool in the nextjs-ai demo:
> fix(ai): ensure interrupt isn't falsy in isInterrupt

- packages/ai-vercel/src/interrupts/errorSerializer.ts
The previous `error.cause` check here was inverted and prevented `Auth0Interrupt` errors from being serialized correctly (and therefore not interrupted).
The logic could be changed to include `!error.cause`, but that's not necessary as `error.cause instanceof Auth0Interrupt` covers that case already (and won't error if error.cause is undefined)
This matches the same logic used elsewhere, eg: https://github.com/auth0-lab/auth0-ai-js/blob/ceaabea989ef7aebfaef1db6f895f053307901d1/packages/ai-vercel/src/interrupts/util.ts#L31-L37
> fix(ai-vercel): ensure Auth0Interrupt errors get serialized

- demos/nextjs-ai/README.md
This pull request focuses on updating the `demos/nextjs-ai/README.md` file by removing references to Okta FGA and simplifying the setup instructions for the Next.js application.
Key changes include:
* Removed the requirement for an Okta FGA account and related setup instructions.
* Deleted environment variable entries related to Okta FGA from the configuration section.
> chore(demos): remove unnecessary config from README on nextjs-ai demo

- packages/ai-genkit/src/FGA/FGAAuthorizer.ts
This pull request includes changes to the `FGAAuthorizer` class in the `packages/ai-genkit/src/FGA/FGAAuthorizer.ts` file to simplify the code and improve maintainability.
Code simplification:
* [`packages/ai-genkit/src/FGA/FGAAuthorizer.ts`](diffhunk://#diff-6919fa3301b57265b62f1a39d60d389b474b126c7b1f4c16bccda0b67c22b46fL6-R6): Removed the `createToolWrapper` import and updated the `authorizer` method to directly return a function that wraps the tool metadata and function with the `protect` method. [[1]](diffhunk://#diff-6919fa3301b57265b62f1a39d60d389b474b126c7b1f4c16bccda0b67c22b46fL6-R6) [[2]](diffhunk://#diff-6919fa3301b57265b62f1a39d60d389b474b126c7b1f4c16bccda0b67c22b46fL32-R34)
> fix(genkit/fga): execute fn is never called

- examples/calling-apis/chatbot/components/auth0-ai/FederatedConnections/FederatedConnectionAuthProps.tsx
- examples/calling-apis/chatbot/components/auth0-ai/FederatedConnections/popup.tsx
- examples/calling-apis/chatbot/components/auth0-ai/FederatedConnections/redirect.tsx
- packages/ai-components/templates/FederatedConnections/FederatedConnectionAuthProps.tsx
- packages/ai-components/templates/FederatedConnections/popup.tsx
- packages/ai-components/templates/FederatedConnections/redirect.tsx
This pull request introduces a new optional property, `containerClassName`, to the `FederatedConnectionAuthProps` type and updates its usage across multiple files. This change allows for additional customization of the container's CSS class.
* [`examples/calling-apis/chatbot/components/auth0-ai/FederatedConnections/FederatedConnectionAuthProps.tsx`](diffhunk://#diff-4f3834a498cb5214c30eda5b899dae9f2daa2c98de76699e8d4685dabc47963aR21): Added `containerClassName` to the `FederatedConnectionAuthProps` type.
* [`packages/ai-components/templates/FederatedConnections/FederatedConnectionAuthProps.tsx`](diffhunk://#diff-4f3834a498cb5214c30eda5b899dae9f2daa2c98de76699e8d4685dabc47963aR21): Added `containerClassName` to the `FederatedConnectionAuthProps` type.
* …
> feat(ai-components): allow containerClassName on EnsureAPIAccess component for styling

- examples/async-user-confirmation/langgraph/README.md
- examples/calling-apis/chatbot/README.md
- examples/calling-apis/chatbot/app/(langgraph)/README.md
- examples/device-flow/langgraph/README.md
This pull request includes several updates to the README files in different examples to improve clarity and accuracy. The changes primarily focus on refining descriptions and instructions related to the LangGraph server and its components.
Improvements to README descriptions and instructions:
* [`examples/async-user-confirmation/langgraph/README.md`](diffhunk://#diff-2d2db2dee3686937c8701ce30cc82f48f4114fa6b9c3a17b8c3fc9dca46ebe35L69-R72): Updated descriptions for LangGraph server components to be more precise and clear.
* [`examples/device-flow/langgraph/README.md`](diffhunk://#diff-55f59e7e6da80c6702c8115336923b03866e776a4dcc3667f71c0078957a4051L68-R71): Similar updates to descriptions for LangGraph server components, ensuring consistency and clarity.
* …
> chore(docs): typos on readme and tiny improvements

- packages/ai-langchain/src/ciba/GraphResumer.ts
- packages/ai/src/interrupts/CIBAInterrupts.ts
- packages/ai/src/interrupts/DeviceInterrupts.ts
- packages/ai/test/ciba/interrupt.test.ts
This pull request includes changes to improve the handling of interrupts in the `ai-langchain` and `ai` packages. The most significant changes involve updating the interrupt classes to use a more flexible type checking mechanism and adding new tests to ensure functionality.
* [`packages/ai-langchain/src/ciba/GraphResumer.ts`](diffhunk://#diff-d5544aa49efeb05c036aaff25adf1e047dc37ab7659be8f6d01427ac4bbf3be5L111-R111): Modified the interrupt check to include `AuthorizationPollingInterrupt` alongside `AuthorizationPendingInterrupt`.
* [`packages/ai/src/interrupts/CIBAInterrupts.ts`](diffhunk://#diff-c50ea2e6eab96e9cd1b9966335476ca8735376cc34949debd7ae5a41e4576f55L17-R25): Updated the `isInterrupt` method in `CIBAInterrupt` to allow for more flexible type checking by including an optional …
> fix: fix isInterrupt for ciba and device flow

- packages/ai-components/bin/cli.js
- packages/ai-components/templates/FederatedConnections/FederatedConnectionAuthProps.tsx
- packages/ai-components/templates/FederatedConnections/index.tsx
- packages/ai-components/templates/FederatedConnections/popup.tsx
- packages/ai-components/templates/FederatedConnections/redirect.tsx
- packages/ai-components/templates/util/prompt-user-container.tsx
This pull request refactors imports across multiple files to explicitly use the `type` keyword for type-only imports, improving code clarity and adhering to best practices. 
It also identifies if the target project uses `./src/components` vs `./components`.
* Updated `FederatedConnectionAuthProps` imports to use the `type` keyword in `FederatedConnectionAuthProps.tsx`, `index.tsx`, `popup.tsx`, and `redirect.tsx`. [[1]](diffhunk://#diff-8c8c398bb48d39b2a04cef38a80cb60a54af27833180afcbf8d2df7bd1c130fcL2-R2) [[2]](diffhunk://#diff-23fe8fb7487fe71205d45207c6dc7894f3d2617276ed1e0bcffbbc5113401117L3-R3) [[3]](diffhunk://#diff-1793e5d5b43409f879dead67e7281c9ab0cfbfc89de660611295c31ee4ee33afL7-R7) [[4]](diffhunk://#diff-7b1fa784a292fa77ead8b1997cae8184405b523fda0d7ab7cb167060b9536a09L4-R4)
* …
> Improve components

- examples/calling-apis/chatbot/app/(langgraph)/lib/tools/list-repositories.ts
This pull request includes a small update to the `listRepositories` function in the `list-repositories.ts` file. The change involves renaming the `accessToken` variable to `credentials` and updating the `auth` property to use `credentials?.accessToken` instead.
* [`list-repositories.ts`](diffhunk://#diff-cb8e686f76c1a464c97ee262edef62633a8c693576bf8f4292f6655bf3d36b57L15-R20): Renamed `accessToken` to `credentials` and updated the GitHub SDK `auth` property to use `credentials?.accessToken` for improved null safety.
> chore(examples): fix calling-apis/chatbot langgraph credential retrieval

- examples/calling-apis/chatbot/components/auth0-ai/FederatedConnections/FederatedConnectionAuthProps.tsx
- examples/calling-apis/chatbot/components/auth0-ai/FederatedConnections/popup.tsx
- examples/calling-apis/chatbot/components/auth0-ai/FederatedConnections/redirect.tsx
- packages/ai-components/templates/FederatedConnections/FederatedConnectionAuthProps.tsx
- packages/ai-components/templates/FederatedConnections/popup.tsx
- packages/ai-components/templates/FederatedConnections/redirect.tsx
This pull request introduces enhancements to the `FederatedConnectionAuthProps` type and updates the `EnsureAPIAccessPopup` and `EnsureAPIAccessRedirect` components to support customizable authentication paths and return URLs. These changes improve flexibility in handling authentication flows for federated connections.
* Added an optional `auth` object to the `FederatedConnectionAuthProps` type, allowing customization of `authorizePath` and `returnTo` values. (`examples/calling-apis/chatbot/components/auth0-ai/FederatedConnections/FederatedConnectionAuthProps.tsx` [[1]](diffhunk://#diff-4f3834a498cb5214c30eda5b899dae9f2daa2c98de76699e8d4685dabc47963aR18-R21) `packages/ai-components/templates/FederatedConnections/FederatedConnectionAuthProps.tsx` …
> feat(ai-compoments): allow authorization path and return to override

- packages/ai-genkit/README.md
- packages/ai-langchain/README.md
- packages/ai-llamaindex/README.md
- packages/ai-vercel/README.md
- packages/ai/src/authorizers/ciba/CIBAAuthorizerBase.ts
- packages/ai/src/authorizers/ciba/CIBAAuthorizerParams.ts
This pull request introduces support for Rich Authorization Requests (RAR) in Client-Initiated Backchannel Authentication (CIBA) across multiple packages and updates the CIBA authorizer implementation to handle RAR parameters. The changes include updates to documentation, new parameters for the CIBA authorizer, and enhancements to the internal authorization logic.
* Added detailed sections on using RAR with CIBA in the `README.md` files for `ai-genkit`, `ai-langchain`, `ai-llamaindex`, and `ai-vercel`. These sections include code examples, setup instructions, and links to relevant Auth0 documentation. [[1]](diffhunk://#diff-f9006b9deabd93286a1ba9ef95c56e9c4c2e9cf0d86c0e62f092f91b66509cc5R195-R225) [[2]](diffhunk://#diff-8fb1cf4cde044d4166b3bda4d69c651c166999d1c6eb19a8b25446dde5036628R221-R …
> feat(ciba): add support for RAR requests for CIBA

- packages/ai/src/authorizers/types.ts
This pull request introduces enhancements to the `Auth0ClientSchema` in `packages/ai/src/authorizers/types.ts` by adding support for optional telemetry and client information fields.
Enhancements to `Auth0ClientSchema`:
* Added a new optional `telemetry` field of type `boolean` to allow configuration of telemetry settings.
* Introduced an optional `clientInfo` field, which is an object containing a `name` property of type `string`, with support for additional properties via `.passthrough()`.
> feat: add auth0 client telemetry config

- packages/ai-genkit/src/Auth0AI.ts
- packages/ai-langchain/src/Auth0AI.ts
- packages/ai-llamaindex/src/Auth0AI.ts
- packages/ai-vercel/src/Auth0AI.ts
- packages/ai/src/authorizers/types.ts
- packages/ai/src/index.ts
This pull request refactors the `AuthorizerParams` type across multiple packages to improve consistency and flexibility by replacing it with `Auth0ClientParams`. Additionally, it updates the `Auth0ClientSchema` to handle optional `clientSecret` values more gracefully. Below are the most important changes grouped by theme:
* Replaced the `AuthorizerParams` type with `Auth0ClientParams` in `Auth0AI.ts` files across the `ai-genkit`, `ai-langchain`, `ai-llamaindex`, and `ai-vercel` packages. This change impacts type definitions for `Auth0AIParams` and the `config` property of the `Auth0AI` class. [[1]](diffhunk://#diff-d689a7f4b8e1648e36cee9b47b2420e4c0d58987d7b54afdc6bd9ffe03a48447L14-R14) [[2]](diffhunk://#diff-d689a7f4b8e1648e36cee9b47b2420e4c0d58987d7b54afdc6bd9ffe03a48447L35-R41) …
> fix: configuration types for auth0

- package-lock.json
- packages/ai-genkit/src/CIBA/CIBAAuthorizer.ts
- packages/ai-langchain/src/ciba/CIBAAuthorizer.ts
- packages/ai/src/authorizers/ciba/CIBAAuthorizerBase.ts
- packages/ai/src/authorizers/ciba/CIBAAuthorizerParams.ts
- packages/ai/test/ciba/ciba-authorizer.test.ts
This pull request introduces enhancements to the `CIBAAuthorizer` classes across multiple packages, focusing on improving the handling of authorization interrupts. The changes include making the `handleAuthorizationInterrupts` method asynchronous, adding a callback for pre-interrupt handling, and updating tests to validate the new functionality.
* **Asynchronous `handleAuthorizationInterrupts` method**:
- Updated the `handleAuthorizationInterrupts` method in `CIBAAuthorizer`, `CIBAAuthorizerBase`, and related classes to be asynchronous, enabling better support for asynchronous operations during interrupt handling. (`[[1]](diffhunk://#diff-aaf1f40ddb28ffa98f2ba6ddc1c10c1935501926c15ab7271b2656b48f4c71e8L28-R28)`, `[[2]](diffhunk://#diff-084b6d97ad16a5aa243637199ee67e893fba0aeb8938c30406e422 …
> feat: add onAuthorizationInterrupt optional callback

- packages/ai-vercel/src/index.ts
This pull request extends the exported functions from the `context` module in the `packages/ai-vercel/src/index.ts` file. The change adds `setGlobalAIContext` to the list of exported functions, enabling broader context management capabilities.
> fix: add missing export setGlobalAIContext

- packages/ai-cloudflare/src/AsyncUserConfirmationResumer.ts
- packages/ai/src/authorizers/ciba/CIBAAuthorizationRequest.ts
This pull request includes updates to improve the handling of asynchronous user confirmation checks and refines documentation for polling intervals. The most important changes involve modifying default delay logic, removing unnecessary context execution, and clarifying comments for better readability.
* [`packages/ai-cloudflare/src/AsyncUserConfirmationResumer.ts`](diffhunk://#diff-35912d4f7bec16d48d3b6116e87f84ca6f6bba36062c4cdbcc9dac91d6273cfaL64-R71): Updated the `scheduleAsyncUserConfirmationCheck` method to use a dynamic default delay based on the `interrupt.request.interval` or fallback to 60 seconds if not provided. This enhances flexibility in scheduling tasks.
* [`packages/ai-cloudflare/src/AsyncUserConfirmationResumer.ts`](diffhunk://#diff-35912d4f7bec16d48d3b6116e87f84ca6f6bba36 …
> fix: remove unnecesary setaicontext and fix polling interval

- examples/async-user-confirmation/llamaindex/package.json
- examples/async-user-confirmation/llamaindex/src/index.ts
- examples/authorization-for-rag/llamaindex/package.json
- examples/authorization-for-tools/llamaindex/package.json
- examples/authorization-for-tools/llamaindex/src/index.ts
- examples/calling-apis/chatbot/app/(llamaindex)/api/llamaindex/route.ts
- examples/calling-apis/chatbot/package.json
- package-lock.json
- packages/ai-llamaindex/package.json
Fixes a breaking change to `llamaindex` w/ `^0.11.28` upgrade in https://github.com/auth0-lab/auth0-ai-js/pull/264.
Previously, our `@auth0/ai-llamaindex` package had been updated to reference llamaindex `^0.11`, however the `examples/` were still referencing `^0.9`.
This addresses the breaking changes to `OpenAIAgent`  w/ that upgrade.
> fix: update llamaindex dep to ^0.11.28

- examples/async-user-confirmation/ai-sdk/src/authorizers/ciba.ts
- examples/async-user-confirmation/ai-sdk/src/authorizers/deviceFlow.ts
- examples/async-user-confirmation/genkit/src/authorizers/ciba.ts
- examples/async-user-confirmation/genkit/src/authorizers/deviceFlow.ts
- examples/async-user-confirmation/llamaindex/src/authorizers/ciba.ts
- examples/async-user-confirmation/llamaindex/src/authorizers/deviceFlow.ts
Ref. https://auth0team.atlassian.net/browse/AIDX-136
> fix: improve deviceflow + ciba chat messages

- package-lock.json
- packages/ai-vercel/package.json
- packages/ai/package.json
- packages/ai/src/authorizers/ciba/CIBAAuthorizerBase.ts
- packages/ai/src/authorizers/ciba/CIBAAuthorizerParams.ts
- packages/ai/src/interrupts/CIBAInterrupts.ts
- packages/ai/test/ciba/ciba-authorizer.test.ts
* For the CIBA Authorizer, renamed `requestExpiry` to `requestedExpiry` and ensured that we send `requested_expiry` to the back-end. This is a breaking change! ⚠️ 
* For the CIBA Authorizer, added handling of the `Retry-After` HTTP response header to determine the next retry interval in the case of error response `slow_down`. The `Retry-After` HTTP header contains an integer value, that is meant to be used as the period of time to wait before polling the endpoint again. So the handling logic will use that value instead of the `interval` value returned previously by the server (just for one time).
ref. https://auth0team.atlassian.net/browse/AIDX-128
> CIBA Fixes: requested_expiry param and Retry-After header handling

- examples/calling-apis/chatbot/app/(langgraph)/api/langgraph/[..._path]/route.ts
Another small change to the passthrough options after reviewing example again today w/ @PavelKorobchuk :
- add `disableWarningLog` to ignore the warning logs about using custom auth approach (we are actually already doing that now, and just opting to still use the passthrough for convenience)
- remove session cookie from forwarded request (it is only needed by the Next.js App Server) and passing this cookie will also sometimes lead to `431 "Request Header Fields Too Large"` error
> fix: update nextjs-api-passthrough options, headers
