- examples/openai-fga/scripts/fga-init.ts
- examples/openai-fga/src/index.ts
Updates the relation in the FGARetriever
And updates the FGA initialization script to avoid overwriting the the model created via interface
> Update relation in FGARetriever

- examples/genkit/retrievers-with-fga/README.md
- examples/genkit/retrievers-with-fga/scripts/fga-init.ts
- examples/langchain/retrievers-with-fga/README.md
- examples/langchain/retrievers-with-fga/scripts/fga-init.ts
- examples/llamaindex/retrievers-with-fga/README.md
- examples/llamaindex/retrievers-with-fga/scripts/fga-init.ts
- examples/openai-fga/README.md
- examples/openai-fga/scripts/fga-init.ts
- examples/openai-fga/src/fga-retriever.ts
- packages/ai-genkit/src/retrievers/fga-retriever.ts
- packages/ai-langchain/src/retrievers/fga-retriever.ts
- packages/ai-llamaindex/src/retrievers/fga-retriever.ts
Use env variables when available, else use US defaults
> Update FGA defaults

- examples/genkit/retrievers-with-fga/.gitignore
- examples/genkit/retrievers-with-fga/helpers/index.ts
- examples/genkit/retrievers-with-fga/index.ts
- packages/ai-genkit/README.md
- packages/ai-genkit/src/index.ts
- packages/ai-genkit/src/retrievers/fga-reranker.ts
- packages/ai-genkit/test/index.test.ts
Refactor genkit retriever to a reranker
> Genkit reranker implementation

- examples/async-user-confirmation/agent-genkit/.npmrc
- examples/async-user-confirmation/agent-genkit/package-lock.json
- examples/async-user-confirmation/agent-genkit/package.json
- examples/async-user-confirmation/agent-genkit/src/context.ts
- examples/async-user-confirmation/agent-genkit/src/index.ts
- examples/async-user-confirmation/agent-genkit/src/tools/buy.ts
- examples/async-user-confirmation/agent-langchain/.npmrc
- examples/async-user-confirmation/agent-langchain/package-lock.json
- examples/async-user-confirmation/agent-langchain/package.json
- examples/async-user-confirmation/agent-langchain/src/index.ts
- examples/async-user-confirmation/agent-langchain/src/tools/buy.ts
- examples/async-user-confirmation/agent-llamaindex/.npmrc
- examples/async-user-confirmation/agent-llamaindex/package-lock.json
- examples/async-user-confirmation/agent-llamaindex/package.json
- examples/async-user-confirmation/agent-llamaindex/src/index.ts
- examples/async-user-confirmation/api/.npmrc
- examples/async-user-confirmation/api/package-lock.json
- packages/ai/src/authorizers/ciba-authorizer.ts
- packages/ai/src/authorizers/device-authorizer.ts
- packages/ai/src/authorizers/fga-authorizer.ts
- packages/ai/src/authorizers/index.ts
- packages/ai/src/errors.ts
- packages/ai/src/errors/authorizationerror.ts
- packages/ai/src/index.ts
- packages/ai/test/ciba-authorizer.test.ts
- packages/ai/test/device-authorizer.test.ts
- packages/ai/test/fga-authorizer.test.ts
This pull request includes several updates and improvements to the `examples/async-user-confirmation` project. The most significant changes involve adding new dependencies, updating existing scripts, and refactoring code for better functionality and maintainability.
* Added `enquirer` dependency to `package.json` and `package-lock.json` for all agents. (`[[1]](diffhunk://#diff-f0aa73ebdee8758f08f3e71dc00d56a078359905881e5be68ecb5d36c787e96dR14-R36)`, `[[2]](diffhunk://#diff-4402ad5e37c2c3253d24067f338315d2096d61664b87edc3ba9120b814137f8fR17)`, `[[3]](diffhunk://#diff-8d56b91d2a7ba6f94781b7d9cc4ad41735cab69988facbbabb58d72376dff9adR18)`)
* Added `ansi-colors`, `ansi-regex`, and `strip-ansi` dependencies to `package-lock.json` for all agents. …
> Error handling

- .vscode/settings.json
- examples/async-user-confirmation/agent-ai-sdk/.npmrc
- examples/async-user-confirmation/agent-ai-sdk/LICENSE
- examples/async-user-confirmation/agent-ai-sdk/README.md
- examples/async-user-confirmation/agent-ai-sdk/package-lock.json
- examples/async-user-confirmation/agent-ai-sdk/package.json
- examples/async-user-confirmation/agent-ai-sdk/src/context.ts
- examples/async-user-confirmation/agent-ai-sdk/src/index.ts
- examples/async-user-confirmation/agent-ai-sdk/src/tools/buy.ts
- examples/async-user-confirmation/agent-llamaindex/src/context.ts
- examples/async-user-confirmation/agent-llamaindex/src/index.ts
- examples/async-user-confirmation/agent-llamaindex/src/tools/buy.ts
- packages/ai/src/index.ts
This pull request includes several changes to the `examples/async-user-confirmation/agent-ai-sdk` directory, focusing on adding a new example agent, setting up necessary configurations, and including licensing information. The most important changes are summarized below:
* [`examples/async-user-confirmation/agent-ai-sdk/package.json`](diffhunk://#diff-36051b9359a67af737b82b26fb4da34ac6184b08beff110d9aaf820dca672a28R1-R21): Added a new `package.json` file to define the project dependencies and scripts.
* [`examples/async-user-confirmation/agent-ai-sdk/package-lock.json`](diffhunk://#diff-4ccba0903ca4bc0f58fadc8ae2eb4302a3e619425040fc7a185cb3a38b324409R1-R343): Added a new `package-lock.json` file to lock the project dependencies.
* …
> adding ai-sdk sample

- demos/nextjs-ai/LICENSE
- demos/nextjs-ai/README.md
- demos/nextjs-ai/app/close/page.tsx
- demos/nextjs-ai/app/page.tsx
- demos/nextjs-ai/components.json
- demos/nextjs-ai/components/auth0/user-button.tsx
- demos/nextjs-ai/components/ui/avatar.tsx
- demos/nextjs-ai/components/ui/button.tsx
- demos/nextjs-ai/components/ui/dropdown-menu.tsx
- demos/nextjs-ai/lib/utils.ts
- demos/nextjs-ai/package.json
- package-lock.json
- package.json
This pull request includes several significant changes to the `demos/nextjs-ai` project, focusing on licensing, UI components, and authentication integration. Below is a summary of the most important changes:
* Added the Apache License 2.0 to the `LICENSE` file.
* Updated the `README.md` file to include a reference to the Apache 2.0 license.
* Introduced a new `Button` component and replaced the existing button element in `PopupClosePage` with the new `Button` component. [[1]](diffhunk://#diff-aa3384c3e9e16decfdbf675de64b5796de7c371b2e2adab72e9a0334dbd1c59fR5-R6) [[2]](diffhunk://#diff-aa3384c3e9e16decfdbf675de64b5796de7c371b2e2adab72e9a0334dbd1c59fL31-R33) [[3]](diffhunk://#diff-d8043b21a266fcf4110d45a5d503cf243ee15dc5a35fe03f20081caba9d488f7R1-R58)
* Added a new `Avatar` component with …
> chore: adding user-menu on nextjs demo

- examples/authorization-for-rag/llamaindex/.npmrc
- examples/authorization-for-rag/llamaindex/package-lock.json
- examples/authorization-for-rag/llamaindex/package.json
- examples/authorization-for-tools/llamaindex/README.md
- examples/authorization-for-tools/llamaindex/package.json
- examples/authorization-for-tools/llamaindex/scripts/fga-init.ts
- examples/authorization-for-tools/llamaindex/src/tools/buy.ts
- package-lock.json
- packages/ai-llamaindex/package.json
- packages/ai-llamaindex/src/FGA/FGAAuthorizer.ts
- packages/ai-llamaindex/src/FGA/index.ts
- packages/ai-llamaindex/src/FGA_AI.ts
- packages/ai-llamaindex/src/index.ts
- packages/ai-llamaindex/tsconfig.json
This pull request includes several changes to the `llamaindex` example and the `ai-llamaindex` package to improve functionality and update dependencies. The most important changes include updates to package dependencies, modifications to authorization logic, and enhancements to the TypeScript configuration.
* [`examples/authorization-for-rag/llamaindex/package.json`](diffhunk://#diff-6cb58049ea850cb1d7e62474016c2633a3860a2f825d48c91fdaedcdac471717L17-R18): Updated the version of `llamaindex` and specified the exact version of `@auth0/ai-llamaindex`.
* [`examples/authorization-for-tools/llamaindex/package.json`](diffhunk://#diff-0cbbcd66f0a3008925336a3306d47150973f93a39d61ea9f3dfb17a8a6405350L16-R16): Updated the version of `llamaindex` and specified the exact version of …
> chore: update auth for tools in llamaindex

- examples/authorization-for-tools/genkit/package-lock.json
- examples/authorization-for-tools/genkit/package.json
- examples/authorization-for-tools/genkit/scripts/fga-init.ts
- examples/authorization-for-tools/genkit/src/tools/buy.ts
- packages/ai-genkit/src/FGA/FGAAuthorizer.ts
- packages/ai-genkit/src/FGA/index.ts
- packages/ai-genkit/src/FGA_AI.ts
- packages/ai-genkit/src/index.ts
- packages/ai-genkit/tsconfig.json
- packages/ai-langchain/src/FGA/FGAAuthorizer.ts
This pull request includes several changes to the `genkit` and `ai-genkit` packages to improve the authorization functionality and update dependencies. The most important changes include updating package dependencies, modifying the `buyTool` function, and introducing new classes for fine-grained authorization.
* Updated `package.json` in `examples/authorization-for-tools/genkit` to replace `@auth0/ai` with `@auth0/ai-genkit` and added `genkitx-openai` dependency.
* Modified the `buyTool` function in `examples/authorization-for-tools/genkit/src/tools/buy.ts` to use the new `Auth0AI` class and updated the logic for unauthorized access messages. [[1]](diffhunk://#diff-4e5e70e8900b70b2c386700fc45590d4404fbaa0106babcd1f563cac9c4e43d7L3-R10) …
> chore: update genkit sdk

- README.md
- examples/async-user-confirmation/README.md
- examples/async-user-confirmation/ai-sdk/README.md
- examples/async-user-confirmation/genkit/README.md
- examples/async-user-confirmation/langchain/README.md
- examples/async-user-confirmation/llamaindex/README.md
- examples/authorization-for-rag/README.md
- examples/authorization-for-rag/genkit/README.md
- examples/authorization-for-rag/langchain/README.md
- examples/authorization-for-rag/langgraph-agentic/README.md
- examples/authorization-for-rag/langgraph-stategraph/README.md
- examples/authorization-for-rag/llamaindex/README.md
- examples/authorization-for-tools/README.md
- examples/authorization-for-tools/ai-sdk/README.md
- examples/authorization-for-tools/genkit/README.md
- examples/authorization-for-tools/langchain/README.md
- examples/authorization-for-tools/llamaindex/README.md
- packages/ai-components/README.md
- packages/ai-genkit/README.md
- packages/ai-langchain/README.md
- packages/ai-llamaindex/README.md
- packages/ai-vercel/README.md
- packages/ai/README.md
This pull request includes updates to the documentation and examples for integrating various AI tools with the `@auth0/ai` library. The changes focus on adding new examples, improving instructions, and providing feedback and contribution guidelines.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R42-R67): Added a new section for `@auth0/ai-components` and detailed instructions for running examples.
* [`examples/async-user-confirmation/README.md`](diffhunk://#diff-8254fc62a007a6a24ead6df7398765329238da392eafbe127123b122faf4eeebL17-R33): Added detailed descriptions and links to examples for integrating `@auth0/ai` with LangChain, LlamaIndex, Genkit, and AI SDK.
* [`examples/authorization-for-tools/README.md`](diffhunk://#diff-69dba31710e200f6 …
> chore(doc): update README files for examples and packages

- demos/vercel-ai-agent/package.json
- demos/vercel-ai-agent/src/tools/buySock.ts
- package-lock.json
- packages/ai-vercel/package.json
This pull request includes several updates to dependencies and refactors a function to improve readability and maintainability. The most important changes include updating the `ai` package version in multiple `package.json` files and refactoring the `buyStock` function in `buySock.ts`.
Dependency updates:
* [`demos/vercel-ai-agent/package.json`](diffhunk://#diff-962c68ed2310e64e35f08c59dfa5523724c8b6dcf657f14eafb89541be373d43L23-R23): Updated the `ai` package version from `4.1.41` to `^4.1.54`.
* [`packages/ai-vercel/package.json`](diffhunk://#diff-58aa606e03887c81c436e799d7cb8d4a0c422a590d7222c9905188dde4cd5afcL51-R55): Moved the `ai` package from `dependencies` to `peerDependencies` and updated its version to `^4.1.54`.
Function refactoring:
* …
> chore: fix vercel-al dependency

- demos/nextjs-ai/README.md
- demos/vercel-ai-agent/README.md
- **chore(doc): update nextjs demo docs**
- **chore(docs): update demo vercel-ai-agent docs**
This pull request includes updates to the README files for two demo applications to provide more detailed setup instructions and information about the technologies used. The most important changes include adding prerequisites, instructions for preparing the workspace, and steps to install and run the applications.
Updates to `demos/nextjs-ai/README.md`:
* Changed the project description to "Chat Application with Auth0 AI and AI SDK" and provided a detailed explanation of the technologies used.
* Added prerequisites, including accounts for Auth0, Okta FGA, and OpenAI.
* Provided instructions for preparing the workspace by copying the `.env.example` file and filling in required values.
* Included …
> chore(doc): update demos documentation and run steps

- demos/vercel-ai-agent/package.json
- demos/vercel-ai-agent/src/queue/index.ts
- demos/vercel-ai-agent/src/worker/handlers/conditional_trade.ts
- demos/vercel-ai-agent/src/worker/index.ts
- packages/ai-vercel/SETUP_INTERRUPTIONS.md
- packages/ai-vercel/src/CIBA/CIBAAuthorizer.ts
- packages/ai-vercel/src/interruptions/index.ts
- packages/ai-vercel/src/interruptions/invokeTools.ts
- packages/ai-vercel/src/interruptions/util.ts
- packages/ai/src/authorizers/ciba/index.ts
- packages/ai/src/errors.ts
This pull request includes various updates and improvements to the `vercel-ai-agent` and `ai-vercel` packages with a focus on enhancing tool invocation handling, error management, and dependency updates.
* [`demos/vercel-ai-agent/src/worker/handlers/conditional_trade.ts`](diffhunk://#diff-73bf4f3fb670686ce51b1c11fa6fda6a8b12434d429fa7af88d8e46f338a05acL1-R1): Integrated new tool invocation logic with `invokeTools` function and improved error handling for `ToolExecutionError` and `Interruption`. [[1]](diffhunk://#diff-73bf4f3fb670686ce51b1c11fa6fda6a8b12434d429fa7af88d8e46f338a05acL1-R1) [[2]](diffhunk://#diff-73bf4f3fb670686ce51b1c11fa6fda6a8b12434d429fa7af88d8e46f338a05acR10-R14) [[3]](diffhunk://#diff-73bf4f3fb670686ce51b1c11fa6fda6a8b12434d429fa7af88d8e46f338a05acR39-R77) …
> chore: fix interruptions in agent demo

- .vscode/settings.json
- demos/vercel-ai-agent/package.json
- demos/vercel-ai-agent/src/queue/index.ts
- examples/async-user-confirmation/langgraph/README.md
- examples/async-user-confirmation/langgraph/package.json
- examples/async-user-confirmation/langgraph/src/agents/agent.ts
- examples/async-user-confirmation/langgraph/src/agents/conditional-trade.ts
- examples/async-user-confirmation/langgraph/src/agents/tools/conditional-trade.ts
- examples/async-user-confirmation/langgraph/src/agents/tools/trade.ts
- examples/async-user-confirmation/langgraph/src/chatbot/index.ts
- package-lock.json
- package.json
- packages/ai-langchain/src/FederatedConnections/FederatedConnectionAuthorizer.ts
- packages/ai/src/authorizers/ciba/CIBAAuthorizerBase.ts
- tools/login-helper/README.md
- tools/login-helper/lib/index.js
- tools/login-helper/package.json
This pull request includes several changes to add new functionalities, improve existing features, and perform code cleanup. The most important changes are grouped into three themes: new features, improvements, and cleanup.
* Added `@auth0/auth0-ai-login-helper` dependency and integrated it into the `demos/vercel-ai-agent` and `examples/async-user-confirmation/langgraph` projects. This includes new imports and usage in the code to handle user login and authentication. [[1]](diffhunk://#diff-962c68ed2310e64e35f08c59dfa5523724c8b6dcf657f14eafb89541be373d43R23) [[2]](diffhunk://#diff-d3f78f3963d211f3cb93584d7e4d533ea98b2c58e77cc188ebab2e84356ffadfR6-R7) [[3]](diffhunk://#diff-d3f78f3963d211f3cb93584d7e4d533ea98b2c58e77cc188ebab2e84356ffadfR56-R60) …
> chore: improve CIBA example for langgraph

- packages/ai-components/package.json
- packages/ai-genkit/package.json
- packages/ai-langchain/package.json
- packages/ai-llamaindex/package.json
- packages/ai-vercel/package.json
- packages/ai/package.json
This pull request includes updates to the descriptions in the `package.json` files for various packages to provide more descriptive and consistent information.
Updated package descriptions:
* [`packages/ai-components/package.json`](diffhunk://#diff-2f50ec3821f5cb76a6ae462829b37d48d92bea37bce79c2d36e7bd0bfcc93472L4-R4): Changed description to "Auth0 AI Components".
* [`packages/ai-genkit/package.json`](diffhunk://#diff-c6a418b63601c8cd1ebb9280658c36c7afce12b9a7444a40705de54d18c1c983L4-R4): Added description "Auth0 AI for GenKit".
* [`packages/ai-langchain/package.json`](diffhunk://#diff-2d0aede74b38e61ff841e237af368e676506ebaf46f123bbe7ed389a86df0bd6L4-R4): Added description "Auth0 AI for LangChain".
* [`packages/ai-llamaindex/package.json`](diffhunk://#diff-a88e0376c9b2001bd301cbaf4fc59baa …
> fix(package): update descriptions

- demos/nextjs-ai/.env.example
- demos/nextjs-ai/README.md
- demos/nextjs-ai/lib/ai/tools/check-user-calendar.ts
- examples/async-user-confirmation/langgraph/README.md
- packages/ai-vercel/README.md
This pull request includes several updates to the `demos/nextjs-ai` project, focusing on improving environment configuration, documentation, and error handling. The most important changes include adding new environment variables, updating the README files for better clarity, and refining error handling in the `check-user-calendar` tool.
Environment configuration updates:
* [`demos/nextjs-ai/.env.example`](diffhunk://#diff-2ab5e45d6698ea578aaae93b8ff727812a709e86ad6d481edab0f9a655ce82b1R5-R6): Added `AUTH0_SECRET` and `APP_BASE_URL` variables to the environment configuration file.
* [`demos/nextjs-ai/.env.example`](diffhunk://#diff-2ab5e45d6698ea578aaae93b8ff727812a709e86ad6d481edab0f9a655ce82b1L22-L24): Removed `NEXT_PUBLIC_URL` variable to clean up the configuration file.
Documentation …
> chore(examples): update demos/nextjs-ai and async user example for langgraph

- examples/async-user-confirmation/genkit/package.json
- examples/async-user-confirmation/genkit/src/index.ts
- examples/async-user-confirmation/genkit/src/tools/buy.ts
- examples/authorization-for-rag/genkit/package.json
- examples/authorization-for-rag/llamaindex/README.md
- examples/authorization-for-tools/genkit/package.json
- examples/authorization-for-tools/genkit/src/index.ts
- examples/authorization-for-tools/genkit/src/tools/buy.ts
- package-lock.json
- packages/ai-genkit/package.json
- packages/ai-genkit/src/Auth0AI.ts
- packages/ai-genkit/src/CIBA/CIBAAuthorizer.ts
- packages/ai-genkit/src/CIBA/index.ts
- packages/ai-genkit/src/FGA/FGAAuthorizer.ts
- packages/ai-genkit/src/FGA/fga-reranker.ts
- packages/ai-genkit/src/FGA_AI.ts
- packages/ai-genkit/src/index.ts
- packages/ai-genkit/src/util/types.ts
This pull request includes several updates across multiple files to upgrade dependencies, refactor code, and enhance functionality. The most important changes are grouped by theme below.
* Upgraded `genkit` dependency to version `^1.3.0` in multiple `package.json` files to ensure compatibility with the latest features. [[1]](diffhunk://#diff-b9ce25136d54dfa376764c4f53290824a21601d47725b7c1a12cf2f1ba98f236L17-R17) [[2]](diffhunk://#diff-6d16ee39dab8084aadd7ea0385dc9dcef1694a1ef748adb011a9f02680d5f233L20-R22) [[3]](diffhunk://#diff-8ac4e84d05ab4c2797be8abfbb61824783e53576b817873242141ada7f38882aL21-R22) [[4]](diffhunk://#diff-c6a418b63601c8cd1ebb9280658c36c7afce12b9a7444a40705de54d18c1c983L37-R37)
* Changed imports from `genkit` to `genkit/beta` in several `index.ts` files to use the beta …
> feat(ai-genkit): upgrade to version 1.3.0 and re-introduce ciba authorizer

- demos/nextjs-ai/README.md
- demos/nextjs-ai/package.json
Also clarify some instructions in the README
> fix(demo): add missing date-fns dependency

- demos/nextjs-ai/app/(genkit)/components/chat.tsx
- demos/nextjs-ai/app/(llamaindex)/api/llamaindex/route.ts
- demos/nextjs-ai/app/(llamaindex)/lib/auth0-ai.ts
- demos/nextjs-ai/app/(llamaindex)/lib/tools/check-user-calendar.ts
- demos/nextjs-ai/app/(llamaindex)/llamaindex/page.tsx
- demos/nextjs-ai/eslint.config.mjs
- packages/ai-llamaindex/package.json
- packages/ai-llamaindex/src/FederatedConnections/FederatedConnectionAuthorizer.ts
- packages/ai-llamaindex/src/interrupts/index.ts
- packages/ai-llamaindex/src/interrupts/with-interruptions.ts
- packages/ai-llamaindex/tsconfig.json
- packages/ai-vercel/src/react/interrupts.ts
- packages/ai/src/interrupts/FederatedConnectionInterrupt.ts
- packages/ai/test/interrupts.test.ts
This pull request includes significant changes to integrate AI functionalities and handle federated connections and interruptions. The main updates involve adding new functionalities to handle user calendar checks, implementing interruption handling, and updating the ESLint configuration.
Integration of AI functionalities:
* [`demos/nextjs-ai/app/(llamaindex)/api/llamaindex/route.ts`](diffhunk://#diff-a8f56048d41656a3e601d4db032c6ebd88d001332f3f55ffd205aceb1a4bafb4R1-R47): Added a new API route to handle POST requests, integrating `OpenAIAgent` and `LlamaIndexAdapter` for AI chat functionalities.
* [`demos/nextjs-ai/app/(llamaindex)/llamaindex/page.tsx`](diffhunk://#diff-8ad6a29b9839c062b58eb696525608ef79e08c38195bc5c7ab95c81262fb3ec7R1-R60): Created a new chat component using `useChat` …
> feat: improve support for federatedTokens in llamaindex

- demos/nextjs-ai/app/(llamaindex)/api/llamaindex/route.ts
This pull request includes changes to the `demos/nextjs-ai/app/(llamaindex)/api/llamaindex/route.ts` file to enhance the functionality of the AI assistant by adding support for chat history.
Enhancements to AI assistant functionality:
* [`demos/nextjs-ai/app/(llamaindex)/api/llamaindex/route.ts`](diffhunk://#diff-a8f56048d41656a3e601d4db032c6ebd88d001332f3f55ffd205aceb1a4bafb4L7-R7): Added import for `ChatMessage` from `llamaindex` to support chat history.
* [`demos/nextjs-ai/app/(llamaindex)/api/llamaindex/route.ts`](diffhunk://#diff-a8f56048d41656a3e601d4db032c6ebd88d001332f3f55ffd205aceb1a4bafb4R30): Modified the `POST` function to include `chatHistory` in the `OpenAIAgent` configuration.
> chore(demo): fix llamaindex history

- examples/calling-apis/chatbot/app/(langgraph)/lib/tools/calendar-view-tool.ts
- examples/calling-apis/chatbot/app/(langgraph)/lib/tools/gmail-search.ts
- packages/ai-langchain/README.md
- packages/ai-langchain/src/Auth0AI.ts
- packages/ai-langchain/src/Device/DeviceAuthorizer.ts
- packages/ai-langchain/src/FGA/FGAAuthorizer.ts
- packages/ai-langchain/src/FGA_AI.ts
- packages/ai-langchain/src/FederatedConnections/FederatedConnectionAuthorizer.ts
- packages/ai-langchain/src/ciba/CIBAAuthorizer.ts
- packages/ai-langchain/src/util/ToolContext.ts
- packages/ai-langchain/src/util/ToolWrapper.ts
This pull request refactors the codebase to replace the use of `DynamicStructuredTool` with a more generalized `StructuredTool` or `ToolLike` interface. The changes improve type safety, simplify the tool abstraction, and reduce dependencies on specific implementations. Below are the most important changes grouped by theme:
* Replaced all instances of `DynamicStructuredTool` with `StructuredTool` in the `Auth0AI` class, including method signatures for `withAsyncUserConfirmation`, `withTokenForConnection`, and `withDeviceAuthorizationFlow`. This ensures consistency and better alignment with the updated tool interface. [[1]](diffhunk://#diff-85272b167a0f51b0605c4296ac671562556340ad226f1fea048cb1aafd39b5b0L1-R1) [[2]](diffhunk://#diff-85272b167a0f51b0605c4296ac671562556340ad226f1fea048cb1aafd3 …
> fix: langgraph types

- packages/ai-vercel/src/context.ts
- packages/ai-vercel/src/index.ts
This pull request introduces a new utility function to manage AI context and updates the exports to include it. The changes ensure better compatibility with environments that do not support `AsyncLocalStorage`.
* [`packages/ai-vercel/src/context.ts`](diffhunk://#diff-9af6051c5be86db9e6b2cd859ee3db8535e5e5b653098355d7b61161f09e9d71R25-R38): Added `runInAIContext` function, which wraps a function in a context and executes it. This is particularly useful for environments like Cloudflare Workers that lack support for `AsyncLocalStorage`.
* [`packages/ai-vercel/src/index.ts`](diffhunk://#diff-cd94228cd80524f6886f2c431d15658cd666d1f9ce66d4efb4bf41d01220cf38L10-R10): Updated exports to include the newly added `runInAIContext` function.
> feat: add runInAIContext to @auth0/ai-vercel

- package-lock.json
- packages/ai-cloudflare/.releaserc.json
- packages/ai-cloudflare/LICENSE
- packages/ai-cloudflare/README.md
- packages/ai-cloudflare/eslint.config.mjs
- packages/ai-cloudflare/package.json
- packages/ai-cloudflare/src/react/index.ts
- packages/ai-cloudflare/test/react/useAgentChatInterruptions.test.ts
- packages/ai-cloudflare/tsconfig.json
This pull request introduces a new package, `@auth0/ai-cloudflare`, which provides tools for integrating Auth0 AI with the Cloudflare Agents SDK. The changes include the addition of configuration files, implementation of core functionality, and documentation to support the package.
* **Core Implementation**: Added the `useAgentChatInterruptions` hook in `src/react/index.ts`, which extends the `useAgentChat` functionality to include interruption handling with the `Auth0InterruptionUI` component. This enables enhanced agent chat workflows.
* **Package Metadata**: Created `package.json` with metadata, dependencies, scripts, and build configurations for the new package. This includes support for TypeScript, linting, and semantic release.
* **TypeScript Configuration**: Added `tsconfig.json` …
> feat: add ai-cloudflare package

- packages/ai-cloudflare/README.md
- packages/ai-cloudflare/src/AsyncUserConfirmationResumer.ts
- packages/ai-cloudflare/src/CloudflareKVStore.ts
- packages/ai-cloudflare/src/index.ts
- packages/ai-vercel/src/Auth0AI.ts
- packages/ai/src/stores/SubStore.ts
This pull request introduces several new features and enhancements to the `ai-cloudflare` package, focusing on improving agent chat functionality, asynchronous user confirmation handling, and Cloudflare KV storage integration. It also includes updates to the `ai` and `ai-vercel` packages to support flexible store implementations.
* Added a custom React hook, `useAgentChatInterruptions`, to handle tool interruptions in agent chat. This extends the existing `useAgentChat` hook. (`[packages/ai-cloudflare/README.mdL16-R18](diffhunk://#diff-05b263a4f46b3ea95f842f108deca48ea441a3c55be46b396361afbebcee4690L16-R18)`)
* Introduced the `AsyncUserConfirmationResumer` mixin to extend `AIChatAgent` for handling asynchronous user confirmations using a scheduling mechanism. This includes methods for …
> AsyncUserConfirmationResumer and CloudflareKVStore for cloudflare

- packages/ai-vercel/src/context.ts
- packages/ai-vercel/src/util/ToolContext.ts
This pull request introduces enhancements to the `ai-vercel` package, focusing on improving context management and ensuring better error handling for thread ID validation. The most significant changes include the addition of global context handling, the deprecation of `runInAIContext` in favor of `runWithAIContext`, and updates to ensure stricter validation in context-related methods.
* **Global Context Support**: Added a global context (`globalContext`) and the `setGlobalAIContext` method to enable context persistence in environments like serverless functions. Includes error handling to prevent overwriting an existing global context with a different thread ID. (`packages/ai-vercel/src/context.ts`, [[1]](diffhunk://#diff-9af6051c5be86db9e6b2cd859ee3db8535e5e5b653098355d7b61161f09e9d71L7-R1 …
> feat: add setGlobalAIContext for @auth0/ai-vercel

- examples/async-user-confirmation/README.md
- examples/async-user-confirmation/langgraph/README.md
Updates async-user-confirmation README link.
> docs: async auth langgraph link

- package-lock.json
- packages/ai-llamaindex/package.json
This pull request updates the `llamaindex` dependency in the `packages/ai-llamaindex/package.json` file to a newer version.
* Dependency update:
* Updated `llamaindex` from version `^0.9.0` to `^0.11` to ensure compatibility with the latest features and fixes.
> feat: update llamaindex version
